[project]
name = "newweb3"
description = "Sustainable Supply Chain Tracker - Stacks dApp"
authors = []
telemetry = false

[contracts.sample]
path = "contracts/sample.clar"
depends_on = []

[contracts.counter]
path = "contracts/counter.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2