[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
balance = 1000000000000000

[accounts.wallet_1]
balance = 1000000000000000

[devnet]
disable_bitcoin_loop = false
bitcoin_controller_automated = true
bitcoin_controller_block_time = 30_000
orchestrator_port = 20443
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18443
stacks_node_p2p_port = 20444
stacks_node_rpc_port = 20443
stacks_api_port = 3999
bitcoin_explorer_port = 8001
stacks_explorer_port = 8000
miner_balance = 1000000000000000