[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 1000000000000000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen praise pork easy bless zero similar vacuum edit glove farm"
balance = 1000000000000000

[devnet]
disable_bitcoin_loop = false
bitcoin_controller_automated = true
bitcoin_controller_block_time = 30_000
orchestrator_port = 20443
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18443
stacks_node_p2p_port = 20444
stacks_node_rpc_port = 20443
stacks_api_port = 3999
bitcoin_explorer_port = 8001
stacks_explorer_port = 8000
miner_mnemonic = "fragile twice sell invite acquire kitten bamboo drastic jelly vivid peace spawn guilt pave pen praise pork easy bless zero similar vacuum edit glove"
miner_balance = 1000000000000000